### ISSUE TITLE
NPE when deleting a function

### ISSUE THREAD

**Issue by ericbottard** [markfisher/sk8s#129]
I managed to get the following NPE several times when using `./faas delete -n echo`:

```
[function-controller-6b98fcd676-htzt8] 2017-11-15 14:26:10.384  WARN 1 --- [default.svc/...] i.f.k.c.d.i.WatchConnectionManager       : Exec Failure
[function-controller-6b98fcd676-htzt8]
[function-controller-6b98fcd676-htzt8] java.lang.NullPointerException: null
[function-controller-6b98fcd676-htzt8] at io.fabric8.kubernetes.client.dsl.internal.DeploymentOperationsImpl$DeploymentReaper.reap(DeploymentOperationsImpl.java:178) ~[kubernetes-client-2.5.9.jar!/:na]
[function-controller-6b98fcd676-htzt8] at io.fabric8.kubernetes.client.dsl.base.BaseOperation.delete(BaseOperation.java:609) ~[kubernetes-client-2.5.9.jar!/:na]
[function-controller-6b98fcd676-htzt8] at io.fabric8.kubernetes.client.dsl.base.BaseOperation.delete(BaseOperation.java:69) ~[kubernetes-client-2.5.9.jar!/:na]
[function-controller-6b98fcd676-htzt8] at io.sk8s.function.controller.FunctionDeployer.undeploy(FunctionDeployer.java:117) ~[classes!/:0.0.1-SNAPSHOT]
[function-controller-6b98fcd676-htzt8] at io.sk8s.function.controller.FunctionMonitor.onFunctionUnregistered(FunctionMonitor.java:101) ~[classes!/:0.0.1-SNAPSHOT]
[function-controller-6b98fcd676-htzt8] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_111-internal]
[function-controller-6b98fcd676-htzt8] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_111-internal]
[function-controller-6b98fcd676-htzt8] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_111-internal]
[function-controller-6b98fcd676-htzt8] at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_111-internal]
[function-controller-6b98fcd676-htzt8] at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:256) ~[spring-context-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
[function-controller-6b98fcd676-htzt8] at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:177) ~[spring-context-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
[function-controller-6b98fcd676-htzt8] at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:140) ~[spring-context-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
[function-controller-6b98fcd676-htzt8] at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
[function-controller-6b98fcd676-htzt8] at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
[function-controller-6b98fcd676-htzt8] at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
[function-controller-6b98fcd676-htzt8] at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393) ~[spring-context-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
[function-controller-6b98fcd676-htzt8] at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:360) ~[spring-context-4.3.12.RELEASE.jar!/:4.3.12.RELEASE]
[function-controller-6b98fcd676-htzt8] at io.sk8s.core.resource.ResourceEventPublisher$ApplicationEventPublishingWatcher.eventReceived(ResourceEventPublisher.java:92) ~[sk8s-core-0.0.1-SNAPSHOT.jar!/:0.0.1-SNAPSHOT]
[function-controller-6b98fcd676-htzt8] at io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager$2.onMessage(WatchConnectionManager.java:230) ~[kubernetes-client-2.5.9.jar!/:na]
[function-controller-6b98fcd676-htzt8] at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:307) ~[okhttp-3.8.1.jar!/:na]
[function-controller-6b98fcd676-htzt8] at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:222) ~[okhttp-3.8.1.jar!/:na]
[function-controller-6b98fcd676-htzt8] at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101) ~[okhttp-3.8.1.jar!/:na]
[function-controller-6b98fcd676-htzt8] at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:262) ~[okhttp-3.8.1.jar!/:na]
[function-controller-6b98fcd676-htzt8] at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:201) ~[okhttp-3.8.1.jar!/:na]
[function-controller-6b98fcd676-htzt8] at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141) [okhttp-3.8.1.jar!/:na]
[function-controller-6b98fcd676-htzt8] at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) [okhttp-3.8.1.jar!/:na]
[function-controller-6b98fcd676-htzt8] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111-internal]
[function-controller-6b98fcd676-htzt8] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111-internal]
[function-controller-6b98fcd676-htzt8] at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111-internal]
```

**Comment by ericbottard** [comment]
After that, the monitor was still logging, which could explain the desynchronization witnessed in #114:
```
function-controller-6b98fcd676-htzt8] 2017-11-15 14:30:14.471 DEBUG 1 --- [       Thread-2] i.s.function.controller.FunctionMonitor  : Subscription{topic='greetings', group='echo'}
[function-controller-6b98fcd676-htzt8] 2017-11-15 14:30:14.471 DEBUG 1 --- [       Thread-2] i.s.function.controller.FunctionMonitor  : 	Offsets{partition=2, endOffset=975, currentOffset=975} Lag=0
[function-controller-6b98fcd676-htzt8] 2017-11-15 14:30:14.471 DEBUG 1 --- [       Thread-2] i.s.function.controller.FunctionMonitor  : 	Offsets{partition=1, endOffset=974, currentOffset=974} Lag=0
[function-controller-6b98fcd676-htzt8] 2017-11-15 14:30:14.471 DEBUG 1 --- [       Thread-2] i.s.function.controller.FunctionMonitor  : 	Offsets{partition=0, endOffset=1009, currentOffset=1009} Lag=0
```

**Comment by ericbottard** [comment]
This appeared on k8s 1.8 so I'm wondering if it could be a race between our call to `FunctionDeployer.delete()` and automatic k8s GC of the deployment. Investigating
